services:
  web:
    build: .
    container_name: app-web
    ports:
      - "8080:80"
    env_file:
      - .env
    volumes:
      - ./app:/var/www/html
      - /mnt/Import-Folder:/mnt/Import-Folder
    depends_on:
      - mysql
    restart: unless-stopped
    # Composer beim Start ausführen (installiert Vendor beim ersten Run)
    command: >
      bash -lc "composer install --no-interaction --prefer-dist &&
                apache2-foreground"

  mysql:
    image: mysql:8.0
    container_name: app-mysql
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d:ro

volumes:
  db_data:
